config/routes.rb
Rails.application.routes.draw do
  resources :answers
  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  devise_for :admins, controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations' }

  get 'choice_client_partner/choice_page'
  post 'choice_client_partner/create'
  get 'kso/index'
  get 'portfolio', to: 'kso#portfolio', as: :portfolio
  get 'bookkeeping', to: 'kso#bookkeeping', as: :bookkeeping
  get 'orders', to: 'kso#orders', as: :orders
  get 'portfolio_add', to: 'kso#portfolio_add', as: :portfolio_add

  resources :profiles, except: [:index]
  post 'profiles/:id/invite' => 'profiles#invite', as: :invite

  get 'cabinet', to: 'users_cabinet#index', as: :cabinet

  resources :tenders do
    resources :reviews do
      resources :comments, only: [:create, :edit]
    end

    resources :questions do
      resources :answers, only: [:create, :edit]
    end

    resources :take_in_competitions, only: [:create, :update]
    resources :requests_for_participation_in_tenders, only: [:index, :create]
  end

  resources :users, only: [:index, :show] do
    # get 'invatee' => 'tenders#invatee', as: :invatee
  end

  namespace :admin do
    get '', to: 'dashboards#show', as: :admin
    get 'profile/:id', to: 'profiles#show', as: :user_profile

    resources :tenders do
      member do
        put 'public_on', to: 'tenders#public_on'
        put 'public_off', to: 'tenders#public_off'
      end

      resources :reviews
    end

    resources :newtender

    resources :users do
      resources :tenders
    end
  end

  root 'front#index'
end

app/models/tender.rb
class Tender < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :take_in_competitions, dependent: :destroy

  enum status: { 'открыт': 1, 'выбор предложений': 2, 'заказ': 3, 'закрыт': 4 } # открыт для заявок, выбор предложений, трансформирован в заказ

  scope :by_user, -> (name) { joins('INNER JOIN users ON tenders.user_id = users.id').order("#{name}") }
  scope :by_title, -> (htitle) { order("#{htitle} DESC") }

  class << self
    def main_purpose
      ['Поддержание имиджа (констатация присутствия, лидерства)',
       'Презентация новинок/стимулирование продаж.',
       'Поддержание партнерских отношений и расширение бизнес-контактов']
    end

    def mainFocus
      ['Логотип/слоган',
       'Продукт/новинку',
       'Ключевое изображение',
       'Концепт-объект (инсталляция, макет, декорация)',
       'Презентационная зона. Зона шоу. Игровая зона']
    end

    def imageSaturation
      ['Максимально',
       'Умеренно',
       'Минимально']
    end

    def openToVisitors
      ['Максимально открытым и просматриваемым',
       'Хорошо просматриваемым с ограниченной зоной доступа',
       'Закрытым']
    end
  end
end

app/controllers/admin/tenders_controller.rb
class Admin::TendersController < ApplicationController
  before_action :authenticate_admin!
  before_action :load_model, only: %i[show edit update destroy public_on]
  layout 'admin'

  def index
    if params[:user_id]
      @user = User.find(params[:user_id])
      @tenders = @user.tenders.order('created_at DESC')
      @one_user = true
    else
      if params[:order_users].blank? && params[:order_htitle].blank?
        @tenders = Tender.order('created_at DESC')
      else
        @tenders = Tender.by_user(params[:order_users]) if params[:order_users]
        @tenders = Tender.by_title(params[:order_htitle]) if params[:order_htitle]
      end
    end
  end

  def show; end

  def new
    @user = User.find(params[:user_id])
    session[:user_id] = @user.id
    @tender = Tender.new
  end

  def create
    @user = User.find(session[:user_id])
    @tender = @user.tenders.build tender_params
    if @tender.save
      redirect_to admin_tenders_path, success: 'Тендер успешно создан'
    else
      flash[:danger] = 'Не удалось создать тендер'
      render :new
    end
  end

  def edit; end

  def update
    if @tender.update tender_params
      redirect_to admin_tenders_path, success: 'Тендер успешно обновлен'
    else
      flash[:danger] = 'Не удалось обновить тендер'
      render :edit
    end
  end

  def destroy
    @tender.destroy
    redirect_to admin_tenders_path, success: 'Тендер удален'
  end

  def public_on
    if @tender.update(public: true)
      @url = tender_url(@tender)
      NewTenderMailer.new_tender(@url, @tender).deliver_later
      redirect_to admin_tenders_path, success: 'Тендер успешно опубликован'
    else
      flash[:danger] = 'Не удалось опубликовать тендер'
      render admin_tenders_path
    end
  end

  private

    def tender_params
      params.require(:tender).permit(
        :budget, :floor, :region, :exhibition, :offer_counter, :obligatory_condition, :company_info,
        :message_count, :technical_specification, :company_info, :main_purpose_participation,
        :main_focus, :special_request, :lighting, :choice_materials, :electrical, :utility_room,
        :negotiation_zone, :additional_equipment, :showcases, :reception, :exhibited_products,
        :height_stand, :open_to_visitors, :image_saturation, :main_focus_stand_more, :area,
        :tender_number_participants, :term_delivery_design_project, :dates_event, :user_id
      )
    end

    def load_model
      @tender = Tender.find params[:id]
    end
end

app/controllers/tenders_controller.rb
class TendersController < ApplicationController
  before_action :authenticate_user!, except: :show
  before_action :load_model, only: %i[show edit update destroy]

  def index
    current_user.partner? ? @tenders = Tender.all : @tenders = current_user.tenders.all
  end

  def show
  end

  def new
    if current_user.partner
      redirect_to cabinet_path(current_user)
    else
      @tender = Tender.new
    end
  end

  def create
    @tender = current_user.tenders.build(tender_params)
    if @tender.save
      redirect_to @tender, success: 'Тендер успешно создан'
    else
      flash[:danger] = 'Не удалось создать тендер'
      render :new
    end
  end

  def edit; end

  def update
    if @tender.update tender_params
      redirect_to tender_path, success: 'Тендер успешно обновлен'
    else
      flash[:danger] = 'Не удалось обновить тендер'
      render :edit
    end
  end

  def destroy
    @tender.destroy
    redirect_to tenders_path, success: 'Тендер удален'
  end

  def invatee
    @user = User.find(params[:user_id])
    if current_user.partner
      @tenders = @user.tenders.where(public: true)
    else
      flash[:danger] = 'Вас пригласили?'
      redirect_to tenders_path
    end
  end

  private

    def tender_params
      params.require(:tender).permit(
        :budget, :floor, :region, :exhibition, :offer_counter, :obligatory_condition, :company_info,
        :message_count, :technical_specification, :company_info, :main_purpose_participation,
        :main_focus, :special_request, :lighting, :choice_materials, :electrical, :utility_room,
        :negotiation_zone, :additional_equipment, :showcases, :reception, :exhibited_products,
        :height_stand, :open_to_visitors, :image_saturation, :main_focus_stand_more, :area,
        :tender_number_participants, :term_delivery_design_project, :dates_event, :user_id
      )
    end

    def load_model
      @tender = Tender.find params[:id]
    end
end

app/helpers/tenders_helper.rb
module TendersHelper
end

app/views/admin/tenders/_form.html.slim
h1 Техническое задание
= simple_form_for [:admin, @tender] do |f|
  = f.input :exhibition, label: 'Выставка'
  = f.input :region,     label: 'Место проведения'
  = f.input :dates_event, label: 'Сроки проведения'
  = f.input :term_delivery_design_project, label: 'Срок сдачи проекта'
  = f.input :budget, label: 'Бюджет(руб)'
  = f.input :tender_number_participants, label: 'Тендер (число участников)'
  h3 Информация о компании (род деятельности):
  = f.input :area, label: 'Площадь стенда'
  = f.input :floor, label: 'Этажность'
  p.mbottom-02rem Площадь 2-го этажа. Длина/ширина. Остов. Полуостров. Угол. Линейный.
  = f.input :company_info, label: 'Зал: Павильон:'
  = f.input :main_purpose_participation, collection: Tender.main_purpose, label: 'Основная цель участия в выставке'
  h3 Основной акцент стенда:
  = f.input :main_focus, collection: Tender.mainFocus, label: 'что должен увидеть Ваш посетитель в первую очередь:'
  p.mbottom-02rem
    | Логотипы и торговые марки, представляемые на стенде:
    br
    | Корпоративные цвета, брендбук:
  = f.input :main_focus_stand_more, label: 'Ассоциации, которые должен вызывать выставочный стенд: (Например, яркий, динамичный и т.п.)'
  h3 В каком стиле Вы хотите видеть стенд:
  = f.input :image_saturation, collection: Tender.imageSaturation, label: 'Насколько стенд должен быть насыщен изображениями (имиджевыми/техническими):'
  = f.input :open_to_visitors, collection: Tender.openToVisitors, label: 'Насколько стенд должен быть открытым для посетителей:'
  = f.input :height_stand, label: 'Высота стенда: (Предпочтения/ограничения по высоте стенда)'
  p.mbottom-02rem
    | Зона ресепшн: (Количество информационных стоек. На сколько человек)
    br
    | Подвес:
    br
    |  Наличие фальшпола/подиума:
    br
    |  Напольное покрытие:
  = f.input :reception, label: 'Зона ресепшн:'
  h3 Экспонируемая продукция:
  = f.input :exhibited_products, label: 'вписать'
  = f.input :showcases, label: 'Наличие витрин (количество, размеры):'
  h3 Оборудование для экспонируемой продукции:
  p.mbottom-02rem Плазменные панели. Проекционные экраны. Другое
  = f.input :additional_equipment, label: 'дополнительное оборудование'
  h3 Переговорные зоны:
  = f.input :negotiation_zone, label: 'Открытая. Закрытая. Площадь. Оснащение мебелью, на сколько человек рассчитано.Взаиморасположение с другими зонами.'
  h3 Подсобное помещение:
  = f.input :utility_room, label: 'Кухня. Раздевалка. Склад. Площадь. Оснащение (стеллаж, вешалка, мойка, кофемашина, холодильник, кулер, корзина).'
  h3 Электрооборудование стенда
  = f.input :electrical, label: 'Экспонаты, требующие подключения, количество розеток:'
  = f.input :choice_materials, label: 'Предпочтения в выборе используемых материалов:'
  = f.input :lighting, label: 'Освещение стенда:'
  h3 Обязательные условия
  = f.input :obligatory_condition, label: 'Например: Собственное производство у компании'
  = f.input :technical_specification, label: 'Общие данные технического задания'
  h3 Дополнительная информация:
  = f.input :special_request, label: 'Особые пожелания к стенду'

  p= f.button :submit, 'Сохранить', class: 'btn btn-primary'

p= link_to 'Назад', :back, class: 'btn btn-light'

app/views/admin/tenders/_tender.html.slim
tr
  td
    = (size - tender_counter) unless (params[:order_users] || params[:order_htitle])
  td= tender.user.company
  td= tender.user.email
  td= tender.exhibition
  td.td-int= tender.area
  td.td-int
    = number_with_precision tender.budget, precision: 2 if tender.budget?
    |  ₽
  td= tender.status
  td= link_to icon('fa-eye', 'посмотреть'), admin_tender_path(tender)
  td
    - if tender.public?
      ' Да
    - else
      = link_to icon('fa-toggle-off i-public-off', 'опубликовать'), public_on_admin_tender_path(tender), method: 'put'
  td= link_to icon('fa-edit', 'редактировать'), edit_admin_tender_path(tender)
  td= link_to icon('fa-trash', 'удалить'), admin_tender_path(tender), method: :delete, data: {confirm: 'Удалить безвозвратно?'}

app/views/admin/tenders/edit.html.slim
= render 'admin/tenders/form'

app/views/admin/tenders/index.html.slim
h1 Тендеры
table.table.table-hover
  thead
    tr
      - if @one_user
        th scope="col" N
        th scope="col" Компания
        th scope="col" E-mail
        th scope="col" Выставка
        th scope="col" Площадь
        th scope="col" Бюджет
        th scope="col" Статус
        th scope="col" Детально
        th scope="col"  Опубликовано
        th scope="col" 
      -else
        th scope="col"= link_to 'N', admin_tenders_path unless @one_user
        th scope="col"= link_to 'Компания', admin_tenders_path(order_users: 'company')
        th scope="col"= link_to 'E-mail', admin_tenders_path(order_users: 'email')
        th scope="col"= link_to 'Выставка', admin_tenders_path(order_htitle: 'exhibition')
        th scope="col"= link_to 'Площадь', admin_tenders_path(order_htitle: 'area')
        th scope="col"= link_to 'Бюджет', admin_tenders_path(order_htitle: 'budget')
        th scope="col" Статус
        th scope="col" Детально
        th scope="col"  Опубликовано
        th scope="col" 
      th scope="col"
      th scope="col"
  tbody
    = render @tenders, size: @tenders.size
p
  - if @user
    = link_to 'Техническое задание', new_admin_user_tender_path(@user), class: 'btn btn-primary'
  - else
    = link_to 'Техническое задание', new_admin_newtender_path, class: 'btn btn-primary'

  = link_to 'Назад', :back, class: 'btn btn-light'

app/views/admin/tenders/new.html.slim
= render 'admin/tenders/form'

app/views/admin/tenders/show.html.slim
table.table.table-hover
  thead
    tr
      th scope="col"  Компания
      th scope="col"  email
      th scope="col"  Выставка
      th scope="col"  Площадь
      th scope="col"  Бюджет
      th scope="col"  Статус
      th scope="col"  Редактировать
      th scope="col"  Удалить
  tbody
    tr
      td= @tender.user.company
      td= @tender.user.email
      td= @tender.exhibition
      td.td-int= @tender.area
      td.td-int
        = number_with_precision @tender.budget, precision: 2 if @tender.budget?
        |  ₽
      td= @tender.status
      td= link_to icon('fa-edit', 'редактировать'), edit_admin_tender_path(@tender)
      td= link_to icon('fa-trash', 'удалить'), admin_tender_path(@tender), method: :delete, data: {confirm: 'Удалить безвозвратно?'}

h4 Место проведени
p= @tender.region

h4 Сроки проведения
p= @tender.dates_event

h4 Срок сдачи проекта
p= @tender.term_delivery_design_project

h4 Тендер (число участников)
p= @tender.tender_number_participants

h4 Этажность
p= @tender.floor

h4 Площадь 2-го этажа. Длина/ширина. Остов. Полуостров. Угол. Линейный.'Зал: Павильон:'
p= @tender.company_info

h4 Основная цель участия в выставке
p= @tender.main_purpose_participation

h4 Основной акцент стенда
p= @tender.main_focus

h4 Ассоциации
p= @tender.main_focus_stand_more

h4 Стиль
p= @tender.image_saturation
p= @tender.open_to_visitors
p= @tender.height_stand

h4 Зона ресепшн
p= @tender.reception

h4 Экспонируемая продукция
p= @tender.exhibited_products

h4 Витрины
p= @tender.showcases

h4 Оборудование для экспонируемой продукции
p= @tender.additional_equipment

h4 Переговорные зоны
p= @tender.negotiation_zone

h4 Подсобное помещение
p= @tender.utility_room

h4 Электрооборудование стенда
p= @tender.electrical

h4 Предпочтения в выборе используемых материалов
p= @tender.choice_materials

h4 Освещение стенда
p= @tender.lighting

h4 Обязательные условия
p= @tender.obligatory_condition

h4 Общие данные технического задания
p= @tender.technical_specification

h4 Дополнительная информация
p= @tender.special_request
p.green
  - if @tender.public?
    ' Тендер опубликован
  - else
    = link_to 'опубликовать', public_on_admin_tender_path(@tender), method: 'put', class: 'btn btn-primary'

p= link_to 'Назад', :back, class: 'btn btn-light'