config/routes.rb
Rails.application.routes.draw do
  resources :answers
  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  devise_for :admins, controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations' }

  get 'choice_client_partner/choice_page'
  post 'choice_client_partner/create'
  get 'kso/index'
  get 'portfolio', to: 'kso#portfolio', as: :portfolio
  get 'bookkeeping', to: 'kso#bookkeeping', as: :bookkeeping
  get 'orders', to: 'kso#orders', as: :orders
  get 'portfolio_add', to: 'kso#portfolio_add', as: :portfolio_add

  resources :profiles, except: [:index]
  post 'profiles/:id/invite' => 'profiles#invite', as: :invite

  get 'cabinet', to: 'users_cabinet#index', as: :cabinet

  resources :tenders do
    resources :reviews do
      resources :comments, only: [:create, :edit]
    end

    resources :questions do
      resources :answers, only: [:create, :edit]
    end

    resources :take_in_competitions, only: [:create, :update]
    resources :requests_for_participation_in_tenders, only: [:index, :create]
  end

  resources :users, only: [:index, :show] do
    # get 'invatee' => 'tenders#invatee', as: :invatee
  end

  namespace :admin do
    get '', to: 'dashboards#show', as: :admin
    get 'profile/:id', to: 'profiles#show', as: :user_profile

    resources :tenders do
      member do
        put 'public_on', to: 'tenders#public_on'
        put 'public_off', to: 'tenders#public_off'
      end

      resources :reviews
    end

    resources :newtender

    resources :users do
      resources :tenders
    end
  end

  root 'front#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question

  mount_uploader :ufile, UfileUploader

  validates :body, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :review

  mount_uploader :ufile, UfileUploader
  # mount_base64_uploader :ufile, UfileUploader

  validates :body, presence: true
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :user
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  mount_uploader :avatar, AvatarUploader
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :tender
  has_many :answers, dependent: :destroy

  mount_uploader :ufile, UfileUploader

  validates :body, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :tender
  belongs_to :user
  has_many :comments, dependent: :destroy

  mount_uploaders :attachments, UfileUploader
  validates :comment, presence: true
end

app/models/tender.rb
class Tender < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :take_in_competitions, dependent: :destroy

  enum status: { 'открыт': 1, 'выбор предложений': 2, 'заказ': 3, 'закрыт': 4 } # открыт для заявок, выбор предложений, трансформирован в заказ

  scope :by_user, -> (name) { joins('INNER JOIN users ON tenders.user_id = users.id').order("#{name}") }
  scope :by_title, -> (htitle) { order("#{htitle} DESC") }

  class << self
    def main_purpose
      ['Поддержание имиджа (констатация присутствия, лидерства)',
       'Презентация новинок/стимулирование продаж.',
       'Поддержание партнерских отношений и расширение бизнес-контактов']
    end

    def mainFocus
      ['Логотип/слоган',
       'Продукт/новинку',
       'Ключевое изображение',
       'Концепт-объект (инсталляция, макет, декорация)',
       'Презентационная зона. Зона шоу. Игровая зона']
    end

    def imageSaturation
      ['Максимально',
       'Умеренно',
       'Минимально']
    end

    def openToVisitors
      ['Максимально открытым и просматриваемым',
       'Хорошо просматриваемым с ограниченной зоной доступа',
       'Закрытым']
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tenders, dependent: :destroy
  has_one :profile, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :invitations, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy

  validates :name, :phone, :company, :agreement, :purpose, presence: true

  scope :partners, -> { where(partner: true).order('created_at DESC') }
  scope :clients, -> { where(partner: false).order('created_at DESC') }
end

app/controllers/kso_controller.rb
class KsoController < ApplicationController
  layout 'kso', except: :portfolio

  def index
  end

  def portfolio
    render layout: 'application'
    end

  def bookkeeping
    render layout: 'application'
    end

  def orders
    render layout: 'application'
    end

  def portfolio_add
    render layout: 'application'
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/front_helper.rb
module FrontHelper
end

app/helpers/kso_helper.rb
module KsoHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tenders_helper.rb
module TendersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/shared/_admin_bar.html.slim
- if admin_signed_in?
  .btn-group.navbar-btn.navbar-right.margin-right-60
    = button_tag class: 'dropdown-toggle btn btn-default', 'data-toggle': 'dropdown' do
      = current_admin.email
      span.caret
    .dropdown-menu aria-labelledby="navbarDropdown"
      = link_to 'Выйти', destroy_admin_session_path, method: :delete, class: 'dropdown-item'
- else
  = link_to 'Вход', new_admin_session_path, class: 'btn btn-default navbar-btn navbar-right'

app/views/layouts/shared/_footer.html.slim
.footer
  / = image_tag('footer.jpg')

app/views/layouts/shared/_main_menu.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light role='navigation'
  .navbar-header
    = link_to root_path, class: 'navbar-brand' do
      = image_tag 'favicon.ico'
      span.logo

  .navbar-collapse.collapse
    - if user_signed_in?
      ul.navbar-nav.mr-auto
        li.nav-item
          - if user_signed_in? && current_user.partner
            = link_to 'Клиенты', users_path, class: 'nav-link'
          - else
            = link_to 'Исполнители', users_path, class: 'nav-link'
        li.nav-item
          = link_to 'Тендеры', tenders_path, class: 'nav-link'
  = render partial: 'layouts/shared/user_bar' unless admin_signed_in?

app/views/layouts/shared/_main_menu_admin.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light role='navigation'
  .navbar-header
    = link_to root_path, class: 'navbar-brand' do
      = image_tag 'favicon.ico'
      span.logo

  .navbar-collapse.collapse
    - if admin_signed_in?
      ul.navbar-nav.mr-auto
        li.nav-item.dropdown role='presentation'
          = link_to '#', class: 'dropdown-toggle nav-link', id: 'navbarDropdown' ,'data-toggle': 'dropdown' do
            | Справочники
            span.caret
          .dropdown-menu aria-labelledby="navbarDropdown"
            = link_to 'example', '#', class: 'dropdown-item'
        li.nav-item
          = link_to 'Клиенты/Партнеры', admin_users_path, class: 'nav-link'
        li.nav-item
          = link_to 'Тендеры', admin_tenders_path, class: 'nav-link'



  = render partial: 'layouts/shared/admin_bar'

app/views/layouts/shared/_panel.html.slim
aside.panel
  nav.panel__nav role='navigation'
    - if user_signed_in?
      header.panel__user-info.user-info
        - if current_user.profile
          .avatar-wrapper
            = image_tag current_user.profile.avatar.url(:thumb), class: 'avatar' unless current_user.profile.avatar.file.nil?
        span.user-info__name= current_user.name
        span.user-info__company= current_user.company
      ul.panel__navigate.panel-navigate
        li.panel-navigate__item
          = link_to 'Главная', root_path, class: 'panel-navigate__link'
        li.panel-navigate__item
          = link_to cabinet_path, class: 'panel-navigate__link' do
            - if current_user.partner
              | личный кабинет
            - else
              | Реализованные проекты
        li.panel-navigate__item
          = link_to 'профиль', profile_path(current_user), class: 'panel-navigate__link'
        li.panel-navigate__item
          = link_to users_path, class: 'panel-navigate__link' do
            - if current_user.partner
              | Клиенты
            - else
              | Партнеры
        li.panel-navigate__item
          = link_to tenders_path, class: 'panel-navigate__link' do
            | Тендеры
            span.panel-navigate__counter
              | 22
        li.panel-navigate__item
          = link_to orders_path, class: 'panel-navigate__link' do
            | Заказы
            span.panel-navigate__counter
              | 22
        li.panel-navigate__item
          = link_to bookkeeping_path, class: 'panel-navigate__link' do
            | Бухгалтерия
        - if current_user.partner
          li.panel-navigate__item
            = link_to portfolio_path, class: 'panel-navigate__link' do
              | Портфолио
        li.panel-navigate__item
          = link_to 'Настройки', edit_user_registration_path, class: 'panel-navigate__link'
        li.panel-navigate__item
          = link_to 'Выход', destroy_user_session_path, method: :delete, class: 'panel-navigate__link'
    - else
      span.user-info__photo
        | Вам необходимо зарегистрироваться
    footer.panel__footer
      span
        | ООО "Идее Группа"
      span
        | ОГРН 11557746876286

app/views/layouts/shared/_user_bar.html.slim
- if user_signed_in?
  .btn-group.navbar-btn.navbar-right.margin-right-60
    = button_tag class: 'dropdown-toggle btn btn-default', 'data-toggle': 'dropdown' do
      = current_user.email
      span.caret
    .dropdown-menu aria-labelledby="navbarDropdown"
      = link_to 'личный кабинет', cabinet_path, class: 'dropdown-item'
      = link_to 'профиль', profile_path(current_user), class: 'dropdown-item'
      = link_to 'Выйти', destroy_user_session_path, method: :delete, class: 'dropdown-item'
      = link_to 'редактировать', edit_user_registration_path, class: 'dropdown-item'
- else
  = link_to 'Войти', new_user_session_path, class: 'nav-link disabled'
  = link_to 'Зарегистрироваться', choice_client_partner_choice_page_path, class: 'nav-link disabled'