config/routes.rb
Rails.application.routes.draw do
  resources :answers
  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  devise_for :admins, controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations' }

  get 'choice_client_partner/choice_page'
  post 'choice_client_partner/create'
  get 'kso/index'
  get 'portfolio', to: 'kso#portfolio', as: :portfolio
  get 'bookkeeping', to: 'kso#bookkeeping', as: :bookkeeping
  get 'orders', to: 'kso#orders', as: :orders
  get 'portfolio_add', to: 'kso#portfolio_add', as: :portfolio_add

  resources :profiles, except: [:index]
  post 'profiles/:id/invite' => 'profiles#invite', as: :invite

  get 'cabinet', to: 'users_cabinet#index', as: :cabinet

  resources :tenders do
    resources :reviews do
      resources :comments, only: [:create, :edit]
    end

    resources :questions do
      resources :answers, only: [:create, :edit]
    end

    resources :take_in_competitions, only: [:create, :update]
    resources :requests_for_participation_in_tenders, only: [:index, :create]
  end

  resources :users, only: [:index, :show] do
    # get 'invatee' => 'tenders#invatee', as: :invatee
  end

  namespace :admin do
    get '', to: 'dashboards#show', as: :admin
    get 'profile/:id', to: 'profiles#show', as: :user_profile

    resources :tenders do
      member do
        put 'public_on', to: 'tenders#public_on'
        put 'public_off', to: 'tenders#public_off'
      end

      resources :reviews
    end

    resources :newtender

    resources :users do
      resources :tenders
    end
  end

  root 'front#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question

  mount_uploader :ufile, UfileUploader

  validates :body, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :review

  mount_uploader :ufile, UfileUploader
  # mount_base64_uploader :ufile, UfileUploader

  validates :body, presence: true
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :user
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  mount_uploader :avatar, AvatarUploader
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :tender
  has_many :answers, dependent: :destroy

  mount_uploader :ufile, UfileUploader

  validates :body, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :tender
  belongs_to :user
  has_many :comments, dependent: :destroy

  mount_uploaders :attachments, UfileUploader
  validates :comment, presence: true
end

app/models/tender.rb
class Tender < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :take_in_competitions, dependent: :destroy

  enum status: { 'открыт': 1, 'выбор предложений': 2, 'заказ': 3, 'закрыт': 4 } # открыт для заявок, выбор предложений, трансформирован в заказ

  scope :by_user, -> (name) { joins('INNER JOIN users ON tenders.user_id = users.id').order("#{name}") }
  scope :by_title, -> (htitle) { order("#{htitle} DESC") }

  class << self
    def main_purpose
      ['Поддержание имиджа (констатация присутствия, лидерства)',
       'Презентация новинок/стимулирование продаж.',
       'Поддержание партнерских отношений и расширение бизнес-контактов']
    end

    def mainFocus
      ['Логотип/слоган',
       'Продукт/новинку',
       'Ключевое изображение',
       'Концепт-объект (инсталляция, макет, декорация)',
       'Презентационная зона. Зона шоу. Игровая зона']
    end

    def imageSaturation
      ['Максимально',
       'Умеренно',
       'Минимально']
    end

    def openToVisitors
      ['Максимально открытым и просматриваемым',
       'Хорошо просматриваемым с ограниченной зоной доступа',
       'Закрытым']
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tenders, dependent: :destroy
  has_one :profile, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :invitations, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy

  validates :name, :phone, :company, :agreement, :purpose, presence: true

  scope :partners, -> { where(partner: true).order('created_at DESC') }
  scope :clients, -> { where(partner: false).order('created_at DESC') }
end

app/controllers/kso_controller.rb
class KsoController < ApplicationController
  layout 'kso', except: :portfolio

  def index
  end

  def portfolio
    render layout: 'application'
    end

  def bookkeeping
    render layout: 'application'
    end

  def orders
    render layout: 'application'
    end

  def portfolio_add
    render layout: 'application'
  end
end

app/controllers/users_cabinet_controller.rb
class UsersCabinetController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = current_user
    @tenders = @user.partner? ? Tender.all : @user.tenders.all
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/front_helper.rb
module FrontHelper
end

app/helpers/kso_helper.rb
module KsoHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tenders_helper.rb
module TendersHelper
end

app/helpers/users_cabinet_helper.rb
module UsersCabinetHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users_cabinet/_client.html.slim
- if @user.profile
  .row
    .col-sm-2
      = image_tag @user.profile.avatar.url(:thumb) unless @user.profile.avatar.file.nil?
h3
  = @user.name
p
  ' E-mail:
  = @user.email
p
  ' Телефон:
  = @user.phone
p
  ' Компания:
  = @user.company
p
  ' Цель:
  = @user.purpose

- if @user.profile
  p= link_to edit_profile_path(current_user) do
    | Редактировать профиль
- else
  p= link_to new_profile_path do
    | Заполнить профиль
p= link_to 'Исправить неверные данные регистрации', edit_user_registration_path
p= link_to 'Техническое задание', new_tender_path, class: 'btn btn-primary'

h3 Мои тендеры
table.mb-5
  thead
    tr
      th scope="col"  Выставка
      th scope="col"  Площадь
      th scope="col"  Бюджет
      th scope="col"  Предложений
      th scope="col"  Статус
      th scope="col"  Детально
      th scope="col"  Редактировать
      th scope="col"  Удалить
  tbody
    - @user.tenders.each do |tender|
      tr class=(tender.public? ? 'public_on' : 'public_off')
        td
          = tender.exhibition
        td.td-int= tender.area
        td.td-int
          = number_with_precision tender.budget, precision: 2 if tender.budget?
          |  ₽
        td.td-int
          - if tender.reviews
            =< tender.reviews.count
          - else
            |  0
        td= tender.status
        td= link_to icon('fa-eye', 'посмотреть'), tender
        td= link_to icon('fa-edit', 'редактировать'), edit_tender_path(tender)
        td= link_to icon('fa-trash', 'удалить'), tender, method: :delete, data: {confirm: 'Удалить безвозвратно?'}

p= link_to 'Назад', :back, class: 'btn btn-light'

app/views/users_cabinet/_partner.html.slim
- if @user.profile
  .row
    .col-sm-2
      = image_tag @user.profile.avatar.url(:thumb) unless @user.profile.avatar.file.nil?
h3
  = @user.name
p
  ' E-mail:
  = @user.email
p
  ' Телефон:
  = @user.phone
p
  ' Компания:
  = @user.company
p
  ' Цель:
  = @user.purpose

- if @user.profile
  p= link_to edit_profile_path(current_user) do
    | Редактировать профиль
- else
  p= link_to new_profile_path do
    | Заполнить профиль
.br /

h3 Тендеры
table.mb-5
  thead
    tr
      th scope="col"  Компания
      th scope="col"  email
      th scope="col"  Выставка
      th scope="col"  Площадь
      th scope="col"  Бюджет
      th scope="col"  Предложений
      th scope="col"  Статус
      th scope="col"  Детально

  tbody
    = render @tenders
p= link_to 'Назад', :back, class: 'btn btn-light'

app/views/users_cabinet/index.html.slim
.profile-wrapper.mb-5
  - if current_user.partner
    = render 'users_cabinet/partner'
  - else
    = render 'users_cabinet/client'