config/routes.rb
Rails.application.routes.draw do
  resources :answers
  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  devise_for :admins, controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations' }

  get 'choice_client_partner/choice_page'
  post 'choice_client_partner/create'
  get 'kso/index'
  get 'portfolio', to: 'kso#portfolio', as: :portfolio
  get 'bookkeeping', to: 'kso#bookkeeping', as: :bookkeeping
  get 'orders', to: 'kso#orders', as: :orders
  get 'portfolio_add', to: 'kso#portfolio_add', as: :portfolio_add

  resources :profiles, except: [:index]
  post 'profiles/:id/invite' => 'profiles#invite', as: :invite

  get 'cabinet', to: 'users_cabinet#index', as: :cabinet

  resources :tenders do
    resources :reviews do
      resources :comments, only: [:create, :edit]
    end

    resources :questions do
      resources :answers, only: [:create, :edit]
    end

    resources :take_in_competitions, only: [:create, :update]
    resources :requests_for_participation_in_tenders, only: [:index, :create]
  end

  resources :users, only: [:index, :show] do
    # get 'invatee' => 'tenders#invatee', as: :invatee
  end

  namespace :admin do
    get '', to: 'dashboards#show', as: :admin
    get 'profile/:id', to: 'profiles#show', as: :user_profile

    resources :tenders do
      member do
        put 'public_on', to: 'tenders#public_on'
        put 'public_off', to: 'tenders#public_off'
      end

      resources :reviews
    end

    resources :newtender

    resources :users do
      resources :tenders
    end
  end

  root 'front#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tenders, dependent: :destroy
  has_one :profile, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :invitations, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy

  validates :name, :phone, :company, :agreement, :purpose, presence: true

  scope :partners, -> { where(partner: true).order('created_at DESC') }
  scope :clients, -> { where(partner: false).order('created_at DESC') }
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  before_action :load_model, only: %i[show edit update destroy]
  layout 'admin'

  def index
    @users = User.all
    @partners = @users.partners
    @users = @users.clients
  end

  def show; end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      redirect_to admin_users_path, success: 'пользователь успешно создан'
    else
      flash[:danger] = 'Не удалось создать пользователя'
      render :new
    end
  end

  def edit; end

  def update
    if @user.update user_params
      redirect_to admin_users_path, success: 'пользователь успешно обновлен'
    else
      flash[:danger] = 'Не удалось обновить пользователя'
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path, success: 'пользователь удален'
  end

  private

    def user_params
      params.require(:user).permit(
        :email, :password, :password_confirmation, :purpose, :partner, :name, :phone, :company, :agreement
      )
    end

    def load_model
      @user = User.find params[:id]
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  layout 'auth'
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  layout 'auth'
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  layout 'auth'
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
  layout 'auth'
  # GET /resource/sign_up
  def new
    @user = User.new
    @user.partner = session[:partner]
  end

  # POST /resource
  def create
    super
    UserMailer.new_registration(resource).deliver_later if resource.save
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:purpose, :partner, :name, :phone, :company, :agreement])
    params.require(:user).permit(:purpose, :email, :password, :password_confirmation, :partner, :name, :phone, :company, :agreement)
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:purpose, :partner, :name, :phone, :company, :agreement])
    params.require(:user).permit(:purpose, :email, :password, :password_confirmation, :partner, :name, :phone, :company, :agreement)
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  layout 'auth'
  # GET /resource/sign_in
  def new
    if admin_signed_in?
      redirect_to admin_admin_path
      return
    else
      super
    end
  end

  # POST /resource/sign_in
  def create
    if admin_signed_in?
      redirect_to admin_admin_path
      return
    else
      super
    end
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  layout 'auth'
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = current_user.partner ? User.clients : User.partners
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= simple_form_for [:admin, @user] do |f| %>

  <div class="form-inputs">
    <%= f.input :email, required: true, autofocus: true %>
    <%= f.input :password, required: true, hint: 'минимум 6 символов' %>
    <%= f.input :password_confirmation, required: true %>
    <%= f.input :phone, required: true, hint: 'По этому номеру сотрудник call-центра подтвердит регистрацию' %>
    <%= f.input :name, required: true %>
    <%= f.input :company, required: true, hint: 'Введите название вашей компании' %>
    <%= f.input :purpose, required: true %>
    <%= f.input :partner %>
  </div>
  <br/>
  <%= f.input :agreement %>
  <p>
    Нажимая кнопку "Регистрация" вы соглашаетесь с
    <%= link_to 'Условиями использования сайта', kso_index_path, target: '_blank' %> и
    <%= link_to 'Условиями использования персональных данных', kso_index_path, target: '_blank' %>
  </p>

  <div class="form-actions">
    <%= f.button :submit, 'OK', class: 'btn btn-large btn-primary' %>
  </div>
<% end %>

app/views/admin/users/_partners.html.slim
table.table.table-hover
  thead
    tr
      th scope="col"  E-mail
      th scope="col"  Имя
      th scope="col"  Телефон
      th scope="col"  Компания
      th scope="col"  удалить
  tbody
    - @partners.each do |partner|
      tr
        td= link_to partner.email, admin_user_profile_path(partner)
        td= partner.name
        td= partner.phone
        td= partner.company
        td= link_to icon('fa-trash', 'удалить'), admin_user_path(partner), method: :delete, data: {confirm: 'Удалить безвозвратно?'}

app/views/admin/users/_tableuser.html.slim
table.table.table-hover
  thead
    tr
      th scope="col"  E-mail
      th scope="col"  Имя
      th scope="col"  Телефон
      th scope="col"  Компания
      th scope="col"  Тендеры
      th scope="col"  удалить
  tbody
    = render @users

app/views/admin/users/_user.html.slim
tr
  td= link_to user.email, admin_user_profile_path(user)
  td= user.name
  td= user.phone
  td= user.company
  td= link_to user.tenders.count, admin_user_tenders_path(user)
  td= link_to icon('fa-trash', 'удалить'), admin_user_path(user), method: :delete, data: {confirm: 'Удалить безвозвратно?'}

app/views/admin/users/edit.html.erb
<h2>Редактировать</h2>
<%= render 'form' %>

app/views/admin/users/index.html.slim
.row
  .col-10
    h1 Клиенты
  .col-2
    = link_to 'Новый', new_admin_user_path, class: 'btn btn-primary'
= render 'admin/users/tableuser'
h3 Партнеры
= render 'admin/users/partners'
p= link_to 'Назад', :back, class: 'btn btn-light'

app/views/admin/users/new.html.erb
<h2>Регистрация</h2>
<%= render 'form' %>